[ice_giant]
    name = 'Ice Giant'
    description = 'One big frosty boi'
    total_health = 250
    current_health = 250

[orc]
    name = 'Orc'
    description = 'A green lean ugly machine'
    total_health = 100
    current_health = 100